@startuml

group POST Solicitud de hora
Paciente -> Servidor : POST BundleSolicitud
activate Servidor
Servidor -> Servidor : Validación
return 
end

group PUT Acepto/Rechazo de hora
Servidor -> Paciente : POST AppointmentResponse
activate Paciente
Paciente -> Paciente : Acepto/Rechazo
return 
end

group PUT Reagendamiento de la hora
Paciente -> Servidor : PUT 
activate Servidor
Servidor -> Servidor : Actualización
return
end

group GET Leer Agenda Propuesta/Confirmada
Paciente -> Servidor : GET Param
activate Servidor
Servidor -> Servidor : Verificación
return 
end

@enduml